# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04c28e08486828d53452b49cf7b72bd6c279900017267ae022e19660c5e0daed21c3d5b3deeecf2b04d5a4e1c4ecd874a2d047c30f18cdb9d625178ed54cfc3d

test:
  secret_key_base: a4b1b51c27a612d7fb15951f4ecb18808eb0a9a857af4f7766b6da06ac86b42a14c8b4f4ea58125a926a85978ed5d9cc3a420cdaee966551de31081e062b1b89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
